### ISSUE TITLE
请求量明明不大，结果却被ban。。。

### ISSUE THREAD

**Issue by playwolf719** [huobiapi/REST-Python3-demo#5]
明明就请求了几次，结果却被ban。。。搞得我以为自己py包有问题，建议这个最好一开始就说明。或者无论什么接口都必须用api key，这样反而能方便进行反爬取，避免伤害到正常用户的使用。

**Comment by huobiapi** [comment]
您好，在请求说明中有建议行情接口加签 https://github.com/huobiapi/API_Docs/wiki/REST_request

**Comment by playwolf719** [comment]
@huobiapi 但是，你们给的api sdk里却给了不加的。。。
